#!/bin/sh

query=$(printf '%s' "$*" | tr ' ' '+' )
movie=$(curl -s https://1337x.wtf/search/$query/1/ | grep -Eo "torrent\/[0-9]{7}\/[a-zA-Z0-9?%-]*/" | head -n 1)
magnet=$(curl -s https://1337x.wtf/$movie | sed -nE 's_.*magnet:\?xt=urn:btih:([^"]*)".*_\1_p' | head -n1)
peerflix -k $magnet
